"""Excel management report.

Builds a single multi-sheet workbook that works the way a business reader
expects: a cover sheet that explains the method, KPI views with market,
product, customer and period drill-downs, the forecast with its accuracy
evidence, the scenario set, and the flat pivot-ready data behind all of it.

Charts are native Excel charts, not images, so they stay live when the reader
filters or extends the data.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Iterable, Sequence

import numpy as np
import pandas as pd

from ..config import Config

# Palette - a restrained, print-safe set with one accent for the forecast.
INK = "#1F2933"
MUTED = "#6B7684"
ACCENT = "#0B7285"
ACCENT_LIGHT = "#8FBFC7"
POSITIVE = "#1F7A4D"
NEGATIVE = "#B4232C"
RULE = "#D8DEE4"
BAND = "#F4F6F8"

SERIES_COLORS = ["#0B7285", "#8A5A2B", "#4C6EF5", "#B4232C",
                 "#1F7A4D", "#7048A8", "#B58900"]


class ReportWorkbook:
    """Thin, opinionated wrapper over XlsxWriter for tabular business reports."""

    def __init__(self, path: str, title: str):
        import xlsxwriter

        self.path = path
        self.book = xlsxwriter.Workbook(path, {"nan_inf_to_errors": True,
                                               "default_date_format": "yyyy-mm-dd"})
        self.book.set_properties({
            "title": title,
            "subject": "EU wholesale market performance and forecast",
            "comments": "Generated by the eu_wholesale analytics pipeline.",
        })
        self.f = self._formats()

    # ------------------------------------------------------------ formats
    def _formats(self) -> dict[str, Any]:
        b = self.book
        base = {"font_name": "Calibri", "font_size": 10}
        return {
            "title": b.add_format({**base, "font_size": 18, "bold": True, "font_color": INK}),
            "subtitle": b.add_format({**base, "font_size": 11, "font_color": MUTED}),
            "h2": b.add_format({**base, "font_size": 12, "bold": True, "font_color": INK,
                                "bottom": 1, "border_color": RULE}),
            "note": b.add_format({**base, "font_color": MUTED, "text_wrap": True,
                                  "valign": "top"}),
            "header": b.add_format({**base, "bold": True, "font_color": "#FFFFFF",
                                    "bg_color": ACCENT, "align": "center",
                                    "valign": "vcenter", "text_wrap": True, "border": 1,
                                    "border_color": ACCENT}),
            "text": b.add_format({**base}),
            "text_bold": b.add_format({**base, "bold": True}),
            "int": b.add_format({**base, "num_format": "#,##0"}),
            "eur0": b.add_format({**base, "num_format": '#,##0;[Red]-#,##0'}),
            "eur1": b.add_format({**base, "num_format": '#,##0.0;[Red]-#,##0.0'}),
            "eur3": b.add_format({**base, "num_format": "#,##0.000"}),
            "price": b.add_format({**base, "num_format": "0.00000"}),
            "pct1": b.add_format({**base, "num_format": '0.0%;[Red]-0.0%'}),
            "pct2": b.add_format({**base, "num_format": "0.00%"}),
            "num1": b.add_format({**base, "num_format": "#,##0.0"}),
            "num2": b.add_format({**base, "num_format": "#,##0.00"}),
            "date": b.add_format({**base, "num_format": "yyyy-mm"}),
            "kpi_value": b.add_format({**base, "font_size": 16, "bold": True,
                                       "font_color": ACCENT, "num_format": "#,##0.0"}),
            "kpi_label": b.add_format({**base, "font_color": MUTED}),
            "pass": b.add_format({**base, "font_color": POSITIVE, "bold": True}),
            "fail": b.add_format({**base, "font_color": NEGATIVE, "bold": True}),
        }

    # ------------------------------------------------------------- sheets
    def sheet(self, name: str, tab_color: str = ACCENT, zoom: int = 100):
        ws = self.book.add_worksheet(name)
        ws.set_tab_color(tab_color)
        ws.hide_gridlines(2)
        ws.set_zoom(zoom)
        return ws

    def heading(self, ws, title: str, subtitle: str = "", row: int = 0) -> int:
        ws.write(row, 0, title, self.f["title"])
        if subtitle:
            ws.write(row + 1, 0, subtitle, self.f["subtitle"])
            return row + 3
        return row + 2

    def section(self, ws, text: str, row: int, width: int = 8) -> int:
        ws.write(row, 0, text, self.f["h2"])
        for c in range(1, width):
            ws.write_blank(row, c, None, self.f["h2"])
        return row + 1

    # -------------------------------------------------------------- table
    def _format_for(self, column: str, series: pd.Series) -> Any:
        col = column.lower()
        if col.endswith("_pct") or col.endswith("_%") or "share" in col or col in {
                "growth_pct", "delta_pct", "margin_pct"}:
            return self.f["pct1"]
        if "eur_m" in col or col.endswith("_eur_m"):
            return self.f["eur1"]
        if col.endswith("_eur") or col in {"mae", "rmse", "actual_eur"}:
            return self.f["eur0"]
        if "price" in col:
            return self.f["price"]
        if col in {"mape", "smape", "wape", "bias_pct"}:
            return self.f["num1"]
        if pd.api.types.is_bool_dtype(series):
            return self.f["text"]
        if pd.api.types.is_integer_dtype(series):
            return self.f["int"]
        if pd.api.types.is_float_dtype(series):
            return self.f["num1"]
        return self.f["text"]

    def table(self, ws, df: pd.DataFrame, row: int, col: int = 0,
              widths: dict[str, int] | None = None,
              autofilter: bool = True, total_row: bool = False,
              header_labels: dict[str, str] | None = None) -> int:
        """Write a dataframe as a formatted block; returns the next free row."""
        widths = widths or {}
        labels = header_labels or {}
        formats = {c: self._format_for(c, df[c]) for c in df.columns}

        for j, c in enumerate(df.columns):
            ws.write(row, col + j, labels.get(c, _humanise(c)), self.f["header"])
            ws.set_column(col + j, col + j, widths.get(c, _auto_width(df[c], c)))

        for i, (_, rec) in enumerate(df.iterrows(), start=1):
            for j, c in enumerate(df.columns):
                _write_cell(ws, row + i, col + j, rec[c], formats[c], self.f["text"])

        end = row + len(df)
        if total_row:
            ws.write(end + 1, col, "Total", self.f["text_bold"])
            for j, c in enumerate(df.columns[1:], start=1):
                if pd.api.types.is_numeric_dtype(df[c]) and not (
                        c.endswith("_pct") or c in {"mape", "smape", "wape", "bias_pct"}):
                    ws.write_formula(
                        end + 1, col + j,
                        f"=SUM({_a1(row + 1, col + j)}:{_a1(end, col + j)})",
                        formats[c], float(df[c].sum(skipna=True)))
            end += 1

        if autofilter and len(df):
            ws.autofilter(row, col, row + len(df), col + len(df.columns) - 1)
        ws.freeze_panes(row + 1, 0)
        return end + 2

    # ------------------------------------------------------------- charts
    def chart(self, ws, kind: str, anchor: str, title: str,
              series: Sequence[dict[str, Any]], *, x_title: str = "",
              y_title: str = "", width: int = 760, height: int = 380,
              subtype: str | None = None, stacked_gap: int | None = None) -> None:
        opts: dict[str, Any] = {"type": kind}
        if subtype:
            opts["subtype"] = subtype
        ch = self.book.add_chart(opts)
        for i, s in enumerate(series):
            spec = dict(s)
            colour = spec.pop("color", SERIES_COLORS[i % len(SERIES_COLORS)])
            dash = spec.pop("dash", None)
            fill = spec.pop("fill", kind in {"column", "bar", "area"})
            line = {"color": colour, "width": 2.0}
            if dash:
                line["dash_type"] = dash
            spec["line"] = line
            if fill:
                spec["fill"] = {"color": colour}
            ch.add_series(spec)
        ch.set_title({"name": title, "name_font": {"size": 12, "bold": True,
                                                   "color": INK, "name": "Calibri"}})
        axis_font = {"size": 9, "color": MUTED, "name": "Calibri"}
        ch.set_x_axis({"name": x_title, "num_font": axis_font,
                       "name_font": axis_font, "line": {"color": RULE}})
        ch.set_y_axis({"name": y_title, "num_font": axis_font,
                       "name_font": axis_font,
                       "major_gridlines": {"visible": True,
                                           "line": {"color": RULE, "width": 0.75}}})
        ch.set_legend({"position": "bottom", "font": axis_font})
        ch.set_chartarea({"border": {"none": True}, "fill": {"color": "#FFFFFF"}})
        ch.set_plotarea({"border": {"none": True}, "fill": {"color": "#FFFFFF"}})
        ch.set_size({"width": width, "height": height})
        if stacked_gap is not None:
            ch.set_gap(stacked_gap)
        ws.insert_chart(anchor, ch)

    def close(self) -> None:
        self.book.close()


# ---------------------------------------------------------------------------
# Cell / layout helpers
# ---------------------------------------------------------------------------
def _write_cell(ws, row: int, col: int, value: Any, fmt, text_fmt) -> None:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        ws.write_blank(row, col, None, fmt)
    elif isinstance(value, (np.integer,)):
        ws.write_number(row, col, int(value), fmt)
    elif isinstance(value, (np.floating, float)):
        ws.write_number(row, col, float(value), fmt)
    elif isinstance(value, (np.bool_, bool)):
        ws.write_string(row, col, "Yes" if bool(value) else "No", text_fmt)
    elif isinstance(value, (pd.Timestamp, datetime)):
        ws.write_datetime(row, col, value, fmt)
    else:
        ws.write_string(row, col, str(value), text_fmt)


def _humanise(name: str) -> str:
    special = {
        "eur": "EUR", "pct": "%", "eur_m": "EUR m", "yoy": "YoY", "mom": "MoM",
        "kpi": "KPI", "id": "ID", "wape": "WAPE", "mape": "MAPE",
        "smape": "sMAPE", "mae": "MAE", "rmse": "RMSE", "r12m": "R12M",
        "hhi": "HHI", "nrr": "NRR", "lo": "Low", "hi": "High", "cagr": "CAGR",
    }
    words = []
    for i, part in enumerate(name.split("_")):
        key = part.lower()
        if key in special:
            words.append(special[key])
        else:
            words.append(part.capitalize() if i == 0 else part.lower())
    return " ".join(words)


def _auto_width(series: pd.Series, column: str) -> int:
    header = len(_humanise(column))
    try:
        longest = int(series.astype(str).str.len().max() or 0)
    except Exception:
        longest = 0
    return int(min(max(header + 3, longest + 2, 10), 42))


def _a1(row: int, col: int) -> str:
    from xlsxwriter.utility import xl_rowcol_to_cell
    return xl_rowcol_to_cell(row, col)


def sheet_range(sheet: str, first_row: int, first_col: int,
                last_row: int, last_col: int) -> list:
    """Chart series reference: ``[sheet, r1, c1, r2, c2]``."""
    return [sheet, first_row, first_col, last_row, last_col]


def eur_m(df: pd.DataFrame, cols: Iterable[str]) -> pd.DataFrame:
    """Rescale EUR columns to millions and rename them accordingly."""
    out = df.copy()
    for c in cols:
        if c in out.columns:
            out[c] = out[c] / 1e6
            out = out.rename(columns={c: c.replace("_eur", "_eur_m")})
    return out

